[package]
name = "wallet_rs"
version = "0.1.0"
authors = ["Charles Cunningham <c.a.cunningham6@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0"
serde_json = "1.0"
thiserror = "1.0"
ursa = { version = "0.3", default-features = false, features = ["portable"]}
bs58 = "0.3"
base64 = "0.12"
uuid = { version = "0.8", features = ["v4"] }
